### ISSUE TITLE
Unable to boot fakezod

### ISSUE THREAD

**Issue by sigilante** [archetype-org/golem#3]
Bug report:  unable to boot a fakezod in a fresh project.

Ubuntu Linux

```
$ golem init
no urbit binary found downloading...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    15    0    15    0     0     53      0 --:--:-- --:--:-- --:--:--    53
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 4304k  100 4304k    0     0  4810k      0 --:--:-- --:--:-- --:--:-- 4810k
tar: Pattern matching characters used in file names
tar: Use --wildcards to enable pattern matching, or --no-wildcards to suppress this warning
tar: /.*/urbit: Not found in archive
tar: Exiting with failure status due to previous errors
Error: Shell command exit with non zero code: 2
    at ChildProcess.<anonymous> (/home/neal/Applications/node-v18.4.0-linux-x64/lib/node_modules/@archetype-org/golem/node_modules/exec-sh/lib/exec-sh.js:73:17)
    at ChildProcess.emit (node:events:537:28)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: 2,
  stdout: '',
  stderr: ''
}
INIT: Creating ship for zod...
booting zod for the first time — may take a while
sh: 1: ./ships/urbit: not found
Error: Shell command exit with non zero code: 127
    at ChildProcess.<anonymous> (/home/neal/Applications/node-v18.4.0-linux-x64/lib/node_modules/@archetype-org/golem/node_modules/exec-sh/lib/exec-sh.js:73:17)
    at ChildProcess.emit (node:events:537:28)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: 127,
  stdout: '',
  stderr: ''
}
INIT: zod created.
INIT: Mounting testing on zod...
No desk found. Attempting to create and mount %testing on zod
Error: Error: connect ENOENT ships/zod/.urb/conn.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1237:16) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'connect',
  address: 'ships/zod/.urb/conn.sock'
}
Error: connect ENOENT ships/zod/.urb/conn.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1237:16) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'connect',
  address: 'ships/zod/.urb/conn.sock'
}
INIT: An error occurred while attempting to create the fakeships: Error: 
  could not create desk %testing on ship ~zod
  Make sure ~zod is running and run the commands:

  |new-desk %testing
  |mount %testing

  in the dojo, before rerunning this command
  
    at isDeskMountedOnShip (file:///home/neal/Applications/node-v18.4.0-linux-x64/lib/node_modules/@archetype-org/golem/lib/checks.js:58:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Command.init (file:///home/neal/Applications/node-v18.4.0-linux-x64/lib/node_modules/@archetype-org/golem/commands/init.js:21:9)
```

**Comment by thisistheaj** [comment]
Taking a look. First hunch is that there may be any number of low-hanging bugs on Ubuntu, all testing has been on macOS so far.

In the meantime — some other issues we have found are self healing if you rerun — did you try running the command a second time and get the same error message?

**Comment by sigilante** [comment]
Repeated attempts yield the same results.  The first error is that `tar: /.*/urbit: Not found in archive`

Ah:

```
    await execShPromise(`curl -L https://urbit.org/install/macos-x86_64/latest | tar xzk -s '/.*/urbit/' && mv ./urbit ./ships/urbit`);
```

That's macOS specific ^
